version: '3'
services:

  postgres:
    image: postgres:13.3
    container_name: postgres-source
    environment:
      POSTGRES_DB: source-db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'


networks:
  mongo_net:
    driver: bridge